### ISSUE TITLE
enable download of high res PNG in addition to pdf

### ISSUE THREAD

**Issue by brinrosenthal** [ucsd-ccbb/shinyGWAS#1]
ideally this would be an option for each figure

**Comment by artnasamran** [comment]
Added buttons and committed changes. However, we'll need to tweak the image parameters. Both plots are set to 1000x1000 pixel 300 DPI resolution .png files. This makes the legends too large on the summary figure. The inner circle on the circos figure becomes distorted
![chr1_circos_20220722](https://user-images.githubusercontent.com/7527403/180574211-ef212280-ec90-4b24-baba-ce6e7837105f.png)
![minChrState_20220722](https://user-images.githubusercontent.com/7527403/180574223-a5f86d15-73b9-4204-9c77-e74aec1c379d.png)
.

**Comment by artnasamran** [comment]
Figured out sizes
